name: Our Workflow
on: push
jobs:
    cache:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
            - name: Cache dilb
              uses: actions/cache@v3
              with:
                  path: ~/.dilb
                  key: ${{ runner.os }}-dilb-${{ hashFiles('**/requirements.txt') }}
            - run: |
                  apt-get install -y --fix-missing \
                  build-essential \
                  cmake \
                  gfortran \
                  git \
                  wget \
                  curl \
                  graphicsmagick \
                  libgraphicsmagick1-dev \
                  libatlas-base-dev \
                  libavcodec-dev \
                  libavformat-dev \
                  libgtk2.0-dev \
                  libjpeg-dev \
                  liblapack-dev \
                  libswscale-dev \
                  pkg-config \
                  python3-dev \
                  python3-numpy \
                  software-properties-common \
                  zip \
                  && apt-get clean && rm -rf /tmp/* /var/tmp/*
                  cd ~ && \
                  mkdir -p dlib && \
                  git clone -b 'v19.9' --single-branch https://github.com/davisking/dlib.git dlib/ && \
                  cd  dlib/ && \
                  python3 setup.py install --yes USE_AVX_INSTRUCTIONS
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 pytest
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
